### PR TITLE
require stable magento-composer-installer

### PR DESCRIPTION
**Pull request by ajpevers**

### CODE REVIEW

**Comment by mage-eag** [comment]
@ajpevers @jappievw
Thanks for your PRs #161 and #162  :)
As both apply to the same part, can you tell me which one I should merge ? (I haven't  used composer with Magento yet)
Or maybe, can we drop the requirement for Magento Composer Installer ? ([here](https://blog.engineyard.com/2014/composer-for-magento) it is recommended to include it, but not in [its repository](https://github.com/Cotya/magento-composer-installer/blob/3.0/doc/MakeAModuleInstallableWithComposer.md))

**Comment by jappievw** [comment]
#161 is a bit more general and allows more developers to use it. So I would advise that one.

**Comment by mage-eag** [comment]
Ok, going for that one, thanks !

**Comment by ajpevers** [comment]
Good work! Thanks!


Met vriendelijke groet,

Anton Evers

Kega
Madame Curiestraat 24 | 2171 TW Sassenheim
Postbus 94 | 2170 AB Sassenheim
T 0252 75 02 40 | F 0252 22 61 72
Skype: ajpevers

anton.evers@kega.nl | www.kega.nl

On Tue, Apr 14, 2015 at 9:15 AM, Benoît <notifications@github.com> wrote:

> Ok, going for that one, thanks !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mage-eag/mage-enhanced-admin-grids/pull/162#issuecomment-92669050>
> .
>

-- 
Volg Kega via social media:

<http://www.twitter.com/kegaretail>   <http://www.linkedin.com/company/kega>
   <http://www.kega.nl/nl/newsletter>

**Pull request closed without merging**
